import type { LayerSpecification } from "maplibre-gl";

import {
  FONT,
  ROAD_MIN_ZOOM,
  ROAD_ORDER,
  ROAD_WIDTH,
  byZoom,
  classIn,
  halo,
  hexId,
  isLine,
  isPolygon,
  named,
  notTunnel,
  pinFootprintLayer,
  ramp,
  roadFilter,
  scaleStops,
  type MapTheme,
  type RoadGroup,
} from "./kit";

/**
 * (c) Dimensional city: San Francisco as a model. Hills shaded from the USGS
 * elevation model in warm late light, buildings standing up in sandstone
 * tones with soft rounded corners, the camera tilting in as you get close,
 * parks a fresher green, and the landmarks and hills marked by name.
 */
const LIGHT = {
  land: "#EFE7DA",
  civic: "#EBE1D1",
  sand: "#EEDDBA",
  park: "#B9CE9A",
  grass: "#C5D7AA",
  wood: "#A3BD86",
  water: "#8DB6C9",
  shallow: "#AFCEDB",
  shadow: "#6B5238",
  highlight: "#FFF8EA",
  building: "#F2E9DA",
  buildingTall: "#DEC6A4",
  road: "#FFFFFF",
  roadCase: "#E2D6C3",
  major: "#FFF4E2",
  motorway: "#F7E0BC",
  rail: "#D5C8B4",
  bridge: "#C8492E",
  label: "#7B6D5B",
  labelStrong: "#554636",
  hood: "#8C7A63",
  parkLabel: "#4D6B37",
  landmark: "#B5532F",
  landmarkLabel: "#6B3F24",
  hill: "#7A6247",
  waterLabel: "#4A7389",
};

type DimensionalPalette = typeof LIGHT;

const DARK: DimensionalPalette = {
  land: "#1B1B1E",
  civic: "#1E1D20",
  sand: "#26241E",
  park: "#223020",
  grass: "#253323",
  wood: "#1F2B1C",
  water: "#0F212B",
  shallow: "#173241",
  shadow: "#000000",
  highlight: "#FFE2B8",
  building: "#34312E",
  buildingTall: "#4F463C",
  road: "#302F2D",
  roadCase: "#232225",
  major: "#3B3834",
  motorway: "#4B4238",
  rail: "#34322F",
  bridge: "#BF4B30",
  label: "#958C80",
  labelStrong: "#CFC4B3",
  hood: "#8F8577",
  parkLabel: "#94B07E",
  landmark: "#E08A5E",
  landmarkLabel: "#E9CDAE",
  hill: "#B9A58A",
  waterLabel: "#7FA6BB",
};

const ROAD_COLOR: Record<RoadGroup, keyof DimensionalPalette> = {
  service: "road",
  minor: "road",
  medium: "road",
  major: "major",
  motorway: "motorway",
};

export const dimensional: MapTheme<DimensionalPalette> = {
  id: "dimensional",
  label: "Dimensional city",
  palettes: { light: LIGHT, dark: DARK },
  tint: {
    land: [0.5, 0.022],
    civic: [0.5, 0.022],
    sand: [0.4, 0.028],
    building: [0.45, 0.026],
    buildingTall: [0.45, 0.03],
    roadCase: [0.45, 0.02],
    park: [0.22, 0.05],
    grass: [0.22, 0.05],
    wood: [0.22, 0.05],
    water: [0.2, 0.05],
    shallow: [0.2, 0.04],
  },
  pitch: 32,
  // Low sun from the west, warm, so the buildings' west faces glow and their east faces fall into shade.
  light: (C, ctx) => ({
    anchor: "map",
    position: [1.3, 270, 50],
    color: ctx.scheme === "dark" ? "#FFD8A8" : "#FFEBD0",
    intensity: ctx.scheme === "dark" ? 0.32 : 0.42,
  }),
  layers(C, ctx) {
    const dark = ctx.scheme === "dark";
    const layers: LayerSpecification[] = [
      { id: "background", type: "background", paint: { "background-color": C.land } },
      {
        id: "landuse",
        type: "fill",
        source: "basemap",
        "source-layer": "landuse",
        minzoom: 12,
        filter: classIn(["hospital", "school", "university", "college"]),
        paint: { "fill-color": C.civic },
      },
      {
        id: "sand",
        type: "fill",
        source: "basemap",
        "source-layer": "landcover",
        filter: ["==", ["get", "class"], "sand"],
        paint: { "fill-color": C.sand },
      },
      { id: "park", type: "fill", source: "basemap", "source-layer": "park", paint: { "fill-color": C.park } },
      {
        id: "greenery",
        type: "fill",
        source: "basemap",
        "source-layer": "landcover",
        filter: classIn(["grass", "wood", "wetland"]),
        paint: { "fill-color": ["match", ["get", "class"], "wood", C.wood, C.grass] },
      },
      ...(ctx.terrain
        ? [
            {
              id: "hills",
              type: "hillshade",
              source: "terrain",
              maxzoom: 17.5,
              paint: {
                "hillshade-method": "igor",
                "hillshade-illumination-direction": 290,
                "hillshade-illumination-anchor": "map",
                "hillshade-exaggeration": dark ? 0.6 : 0.5,
                "hillshade-shadow-color": dark ? "rgba(0,0,0,0.55)" : `${C.shadow}66`,
                "hillshade-highlight-color": dark ? "rgba(255,226,184,0.06)" : `${C.highlight}88`,
                "hillshade-accent-color": dark ? "rgba(0,0,0,0.25)" : `${C.shadow}22`,
              },
            } satisfies LayerSpecification,
          ]
        : []),
      {
        id: "water",
        type: "fill",
        source: "basemap",
        "source-layer": "water",
        filter: notTunnel,
        paint: { "fill-color": C.water },
      },
      {
        id: "water-shallows",
        type: "line",
        source: "basemap",
        "source-layer": "water",
        minzoom: 10,
        filter: ["all", notTunnel, classIn(["ocean", "river"])],
        layout: { "line-join": "round" },
        paint: {
          "line-color": C.shallow,
          "line-width": ramp([[10, 3], [14, 8], [16, 14]]),
          "line-offset": ramp([[10, 2], [14, 4.5], [16, 7.5]]),
          "line-blur": ramp([[10, 3], [14, 7], [16, 12]]),
          "line-opacity": 0.85,
        },
      },
      {
        id: "pier",
        type: "fill",
        source: "basemap",
        "source-layer": "transportation",
        filter: ["all", isPolygon, ["==", ["get", "class"], "pier"]],
        paint: { "fill-color": C.land },
      },
      {
        id: "rail",
        type: "line",
        source: "basemap",
        "source-layer": "transportation",
        minzoom: 13,
        filter: ["all", isLine, classIn(["rail", "transit"]), notTunnel],
        paint: { "line-color": C.rail, "line-width": ramp([[13, 0.8], [16, 1.4], [19, 2.4]]) },
      },
      // Soft casings give the streets a little lift off the land.
      ...ROAD_ORDER.filter((g) => g !== "service").map<LayerSpecification>((g) => ({
        id: `road-case-${g}`,
        type: "line",
        source: "basemap",
        "source-layer": "transportation",
        minzoom: Math.max(ROAD_MIN_ZOOM[g], 12),
        filter: roadFilter(g),
        layout: { "line-cap": "round", "line-join": "round" },
        paint: {
          "line-color": C.roadCase,
          "line-width": ramp(scaleStops(ROAD_WIDTH[g], 1.35)),
          "line-opacity": byZoom(12, 0, 13.5, 1),
        },
      })),
      ...ROAD_ORDER.map<LayerSpecification>((g) => ({
        id: `road-${g}`,
        type: "line",
        source: "basemap",
        "source-layer": "transportation",
        minzoom: ROAD_MIN_ZOOM[g],
        filter: roadFilter(g),
        layout: { "line-cap": "round", "line-join": "round" },
        paint: {
          "line-color": g === "minor" || g === "service" ? byZoom(11, C.roadCase, 13.5, C.road) : C[ROAD_COLOR[g]],
          "line-width": ramp(ROAD_WIDTH[g]),
        },
      })),
      {
        id: "golden-gate-bridge",
        type: "line",
        source: "basemap",
        "source-layer": "transportation_name",
        filter: ["all", isLine, ["==", ["get", "name"], "Golden Gate Bridge"], ["==", ["get", "class"], "motorway"]],
        paint: { "line-color": C.bridge, "line-width": ramp([[9, 1.8], [12, 3.4], [15, 8], [17, 16]]) },
      },
      // Buildings rise as you zoom in, taller ones a deeper sandstone.
      {
        id: "buildings-3d",
        type: "fill-extrusion",
        source: "basemap",
        "source-layer": "building",
        minzoom: 14,
        layout: { "fill-extrusion-rounded-corner-distance": 1.5 },
        paint: {
          "fill-extrusion-color": [
            "interpolate",
            ["linear"],
            ["coalesce", ["get", "render_height"], 6],
            6,
            C.building,
            120,
            C.buildingTall,
          ],
          "fill-extrusion-height": [
            "interpolate",
            ["linear"],
            ["zoom"],
            14,
            0,
            15.2,
            ["coalesce", ["get", "render_height"], 6],
          ],
          "fill-extrusion-base": ["coalesce", ["get", "render_min_height"], 0],
          "fill-extrusion-opacity": 0.9,
          "fill-extrusion-vertical-gradient": true,
        },
      },
      {
        id: "water-label",
        type: "symbol",
        source: "basemap",
        "source-layer": "water_name",
        filter: ["==", ["geometry-type"], "Point"],
        layout: {
          "text-field": ["get", "name"],
          "text-font": FONT.medium,
          "text-size": byZoom(8, 11, 14, 14),
          "text-letter-spacing": 0.08,
          "text-max-width": 6,
        },
        paint: { "text-color": C.waterLabel, "text-halo-color": halo(C.water, "aa"), "text-halo-width": 1 },
      },
      {
        id: "road-label",
        type: "symbol",
        source: "basemap",
        "source-layer": "transportation_name",
        minzoom: 15,
        filter: classIn(["motorway", "trunk", "primary", "secondary", "tertiary"]),
        layout: {
          "text-field": ["get", "name"],
          "text-font": FONT.sans,
          "text-size": byZoom(15, 10.5, 17, 12),
          "symbol-placement": "line",
          "text-padding": 14,
          "text-pitch-alignment": "viewport",
        },
        paint: { "text-color": C.label, "text-halo-color": halo(C.road), "text-halo-width": 1.4 },
      },
      {
        id: "park-label",
        type: "symbol",
        source: "basemap",
        "source-layer": "poi",
        minzoom: 12.5,
        filter: ["all", classIn(["park", "national_park", "garden"]), named],
        layout: {
          "text-field": ["get", "name"],
          "text-font": FONT.semibold,
          "text-size": byZoom(12.5, 11, 16, 13),
          "text-max-width": 8,
          "text-padding": 8,
        },
        paint: { "text-color": C.parkLabel, "text-halo-color": halo(C.park, "d9"), "text-halo-width": 1.4 },
      },
      {
        id: "neighborhood-label",
        type: "symbol",
        source: "basemap",
        "source-layer": "place",
        minzoom: 12,
        maxzoom: 15.5,
        filter: classIn(["neighbourhood", "suburb", "quarter"]),
        layout: {
          "text-field": ["get", "name"],
          "text-font": FONT.medium,
          "text-size": byZoom(12, 11, 15, 13),
          "text-max-width": 7,
          "text-padding": 10,
        },
        paint: {
          "text-color": C.hood,
          "text-halo-color": halo(C.land),
          "text-halo-width": 1.4,
          "text-opacity": byZoom(14.5, 1, 15.5, 0),
        },
      },
      {
        id: "hill-label",
        type: "symbol",
        source: "landmarks",
        minzoom: 11.5,
        filter: ["all", ["==", ["get", "kind"], "hill"], ["any", ["==", ["get", "rank"], 1], [">=", ["zoom"], 13.5]]],
        layout: {
          "icon-image": `peak-${hexId(C.hill)}`,
          "icon-size": 0.9,
          "text-field": ["get", "name"],
          "text-font": FONT.medium,
          "text-size": byZoom(11.5, 10.5, 15, 12.5),
          "text-anchor": "top",
          "text-offset": [0, 0.7],
          "text-padding": 6,
        },
        paint: { "text-color": C.hill, "text-halo-color": halo(C.land), "text-halo-width": 1.4 },
      },
      {
        id: "landmark-label",
        type: "symbol",
        source: "landmarks",
        minzoom: 11,
        filter: ["all", ["==", ["get", "kind"], "landmark"], ["any", ["==", ["get", "rank"], 1], [">=", ["zoom"], 13.5]]],
        layout: {
          "icon-image": `landmark-${hexId(C.landmark)}`,
          "text-field": ["upcase", ["get", "name"]],
          "text-font": FONT.semibold,
          "text-size": byZoom(11, 9.5, 15, 11.5),
          "text-letter-spacing": 0.08,
          "text-anchor": "top",
          "text-offset": [0, 0.8],
          "text-max-width": 9,
          "text-padding": 6,
          "symbol-sort-key": ["get", "rank"],
        },
        paint: { "text-color": C.landmarkLabel, "text-halo-color": halo(C.land), "text-halo-width": 1.6 },
      },
      {
        id: "city-label",
        type: "symbol",
        source: "basemap",
        "source-layer": "place",
        maxzoom: 12,
        filter: classIn(["city", "town"]),
        layout: {
          "text-field": ["get", "name"],
          "text-font": FONT.semibold,
          "text-size": byZoom(6, 11, 11, 15),
          "text-max-width": 8,
        },
        paint: { "text-color": C.labelStrong, "text-halo-color": halo(C.land), "text-halo-width": 1.4 },
      },
      pinFootprintLayer(),
    ];
    return layers;
  },
};
