import type { LayerSpecification } from "maplibre-gl";

import {
  FONT,
  ROAD_MIN_ZOOM,
  ROAD_ORDER,
  ROAD_WIDTH,
  byZoom,
  classIn,
  halo,
  hexId,
  isLine,
  isPolygon,
  named,
  notTunnel,
  pinFootprintLayer,
  ramp,
  roadFilter,
  type MapTheme,
  type RoadGroup,
} from "./kit";

/**
 * (a) Golden hour film: the city in late warm light, like the Kodak photos.
 * Warm cream land, a deep teal bay that pales toward the shore over a sandy
 * edge, sage and olive parks with a fine grain, terracotta and ochre
 * arterials, soft building footprints, and the bridge in International Orange.
 */
const LIGHT = {
  land: "#F4E8D3",
  civic: "#F0E1C8",
  industrial: "#EADFCD",
  sand: "#EFD8AC",
  park: "#C1C893",
  grass: "#CCD1A0",
  wood: "#A9B67F",
  grain: "#5F6B32",
  water: "#4C8894",
  shallow: "#7FB1B3",
  shore: "#E6CB98",
  building: "#EBDCC2",
  buildingEdge: "#DFCBA8",
  road: "#FFFAF1",
  roadFar: "#EBDDC6",
  medium: "#F6E0BD",
  major: "#E9B488",
  motorway: "#DC9A6B",
  tunnel: "#F3E6D1",
  rail: "#D2BE9C",
  path: "#DCC9A9",
  bridge: "#C8492E",
  label: "#7D6A54",
  labelStrong: "#5B4A38",
  hood: "#8E7859",
  parkLabel: "#5D6B38",
  waterLabel: "#E4F1EE",
};

type GoldenPalette = typeof LIGHT;

const DARK: GoldenPalette = {
  land: "#1F1B16",
  civic: "#221D17",
  industrial: "#211E1A",
  sand: "#2C261C",
  park: "#2A3121",
  grass: "#2D3424",
  wood: "#252D1C",
  grain: "#9AAA6A",
  water: "#173A42",
  shallow: "#22505A",
  shore: "#3A3021",
  building: "#2A241D",
  buildingEdge: "#342C22",
  road: "#312B24",
  roadFar: "#27221C",
  medium: "#4A3A28",
  major: "#6B4A2F",
  motorway: "#7E5333",
  tunnel: "#27221C",
  rail: "#3A3226",
  path: "#352E25",
  bridge: "#B8452D",
  label: "#A39580",
  labelStrong: "#CBBDA6",
  hood: "#9C8C74",
  parkLabel: "#A4B283",
  waterLabel: "#8CBFC2",
};

const ROAD_COLOR: Record<RoadGroup, keyof GoldenPalette> = {
  service: "road",
  minor: "road",
  medium: "medium",
  major: "major",
  motorway: "motorway",
};

/** Half the width plus a pixel: an inset or outset line that sits wholly on one side of a shore. */
const half = (stops: [number, number][], sign: 1 | -1) =>
  ramp(stops.map(([z, w]) => [z, sign * (w / 2 + 0.5)]));

export const golden: MapTheme<GoldenPalette> = {
  id: "golden",
  label: "Golden hour film",
  palettes: { light: LIGHT, dark: DARK },
  tint: {
    land: [0.5, 0.022],
    civic: [0.5, 0.022],
    industrial: [0.5, 0.02],
    sand: [0.4, 0.03],
    building: [0.5, 0.024],
    road: [0.45, 0.01],
    roadFar: [0.45, 0.02],
    park: [0.25, 0.05],
    grass: [0.25, 0.05],
    wood: [0.25, 0.05],
    water: [0.2, 0.06],
    shallow: [0.2, 0.05],
  },
  pitch: 0,
  layers(C, ctx) {
    const dark = ctx.scheme === "dark";
    const shallow: [number, number][] = [[9, 3], [12, 8], [14, 14], [16, 24]];
    const shore: [number, number][] = [[9, 0.6], [12, 1.4], [15, 3]];
    const layers: LayerSpecification[] = [
      { id: "background", type: "background", paint: { "background-color": C.land } },
      {
        id: "landuse",
        type: "fill",
        source: "basemap",
        "source-layer": "landuse",
        minzoom: 11,
        filter: classIn(["hospital", "school", "university", "college", "industrial", "railway"]),
        paint: {
          "fill-color": ["match", ["get", "class"], ["industrial", "railway"], C.industrial, C.civic],
          "fill-opacity": byZoom(11, 0, 13, 1),
        },
      },
      {
        id: "sand",
        type: "fill",
        source: "basemap",
        "source-layer": "landcover",
        filter: ["==", ["get", "class"], "sand"],
        paint: { "fill-color": C.sand },
      },
      { id: "park", type: "fill", source: "basemap", "source-layer": "park", paint: { "fill-color": C.park } },
      {
        id: "greenery",
        type: "fill",
        source: "basemap",
        "source-layer": "landcover",
        filter: classIn(["grass", "wood", "wetland"]),
        paint: { "fill-color": ["match", ["get", "class"], "wood", C.wood, C.grass] },
      },
      {
        id: "pitch",
        type: "fill",
        source: "basemap",
        "source-layer": "landuse",
        minzoom: 13,
        filter: classIn(["pitch", "playground"]),
        paint: { "fill-color": C.grass, "fill-opacity": 0.8 },
      },
      // Film grain over the parks, a little stronger in the woods.
      {
        id: "park-grain",
        type: "fill",
        source: "basemap",
        "source-layer": "park",
        minzoom: 11,
        paint: { "fill-pattern": `stipple-${hexId(C.grain)}-${dark ? 22 : 16}`, "fill-opacity": byZoom(11, 0, 12.5, 1) },
      },
      {
        id: "wood-grain",
        type: "fill",
        source: "basemap",
        "source-layer": "landcover",
        minzoom: 11,
        filter: ["==", ["get", "class"], "wood"],
        paint: { "fill-pattern": `stipple-${hexId(C.grain)}-${dark ? 34 : 26}`, "fill-opacity": byZoom(11, 0, 12.5, 1) },
      },
      {
        id: "water",
        type: "fill",
        source: "basemap",
        "source-layer": "water",
        filter: notTunnel,
        paint: { "fill-color": C.water },
      },
      // Shallows: the water pales in a soft band along every shore.
      {
        id: "water-shallows",
        type: "line",
        source: "basemap",
        "source-layer": "water",
        minzoom: 9,
        filter: ["all", notTunnel, ["!=", ["get", "class"], "swimming_pool"]],
        layout: { "line-join": "round" },
        paint: {
          "line-color": C.shallow,
          "line-width": ramp(shallow),
          "line-offset": half(shallow, 1),
          "line-blur": ramp(shallow.map(([z, w]) => [z, w * 0.9])),
          "line-opacity": 0.8,
        },
      },
      {
        id: "shoreline",
        type: "line",
        source: "basemap",
        "source-layer": "water",
        minzoom: 10,
        filter: ["all", notTunnel, classIn(["ocean", "river", "dock"])],
        layout: { "line-join": "round" },
        paint: {
          "line-color": C.shore,
          "line-width": ramp(shore),
          "line-offset": half(shore, -1),
          "line-blur": 0.8,
        },
      },
      {
        id: "waterway",
        type: "line",
        source: "basemap",
        "source-layer": "waterway",
        minzoom: 12,
        paint: { "line-color": C.water, "line-width": ramp([[12, 0.5], [16, 1.5], [18, 3]]) },
      },
      {
        id: "pier",
        type: "fill",
        source: "basemap",
        "source-layer": "transportation",
        filter: ["all", isPolygon, ["==", ["get", "class"], "pier"]],
        paint: { "fill-color": C.land },
      },
      {
        id: "building",
        type: "fill",
        source: "basemap",
        "source-layer": "building",
        minzoom: 14.5,
        paint: {
          "fill-color": C.building,
          "fill-outline-color": C.buildingEdge,
          "fill-opacity": byZoom(14.5, 0, 15.5, 1),
        },
      },
      {
        id: "path",
        type: "line",
        source: "basemap",
        "source-layer": "transportation",
        minzoom: 15,
        filter: ["all", isLine, ["==", ["get", "class"], "path"], notTunnel],
        paint: {
          "line-color": C.path,
          "line-width": ramp([[15, 0.8], [17, 1.6], [19, 3]]),
          "line-dasharray": [2, 1.5],
        },
      },
      {
        id: "rail",
        type: "line",
        source: "basemap",
        "source-layer": "transportation",
        minzoom: 13,
        filter: ["all", isLine, classIn(["rail", "transit"]), notTunnel],
        paint: {
          "line-color": C.rail,
          "line-width": ramp([[13, 0.8], [16, 1.4], [19, 2.4]]),
          "line-dasharray": [3, 2],
        },
      },
      ...ROAD_ORDER.map<LayerSpecification>((g) => ({
        id: `road-${g}`,
        type: "line",
        source: "basemap",
        "source-layer": "transportation",
        minzoom: ROAD_MIN_ZOOM[g],
        filter: roadFilter(g),
        layout: { "line-cap": "round", "line-join": "round" },
        paint: {
          // Far out, the cream streets would vanish into the land; they warm until there's room.
          "line-color":
            g === "minor" || g === "service" ? byZoom(11, C.roadFar, 14, C.road) : C[ROAD_COLOR[g]],
          "line-width": ramp(ROAD_WIDTH[g]),
        },
      })),
      {
        id: "golden-gate-bridge",
        type: "line",
        source: "basemap",
        "source-layer": "transportation_name",
        filter: ["all", isLine, ["==", ["get", "name"], "Golden Gate Bridge"], ["==", ["get", "class"], "motorway"]],
        layout: { "line-cap": "butt" },
        paint: { "line-color": C.bridge, "line-width": ramp([[9, 1.6], [12, 3], [15, 7], [17, 15]]) },
      },
      {
        id: "water-label",
        type: "symbol",
        source: "basemap",
        "source-layer": "water_name",
        filter: ["==", ["geometry-type"], "Point"],
        layout: {
          "text-field": ["get", "name"],
          "text-font": FONT.medium,
          "text-size": byZoom(8, 11, 14, 14),
          "text-letter-spacing": 0.06,
          "text-max-width": 6,
        },
        paint: { "text-color": C.waterLabel, "text-halo-color": halo(C.water, "99"), "text-halo-width": 1 },
      },
      {
        id: "road-label",
        type: "symbol",
        source: "basemap",
        "source-layer": "transportation_name",
        minzoom: 14,
        filter: [
          "any",
          classIn(["motorway", "trunk", "primary", "secondary", "tertiary"]),
          ["all", classIn(["minor"]), [">=", ["zoom"], 15.5]],
        ],
        layout: {
          "text-field": ["get", "name"],
          "text-font": FONT.sans,
          "text-size": byZoom(14, 10.5, 17, 12.5),
          "symbol-placement": "line",
          "text-padding": 12,
        },
        paint: { "text-color": C.label, "text-halo-color": halo(C.land), "text-halo-width": 1.2 },
      },
      {
        id: "park-label",
        type: "symbol",
        source: "basemap",
        "source-layer": "poi",
        minzoom: 13,
        filter: ["all", classIn(["park", "national_park", "garden"]), named],
        layout: {
          "text-field": ["get", "name"],
          "text-font": FONT.medium,
          "text-size": byZoom(13, 11, 16, 13),
          "text-max-width": 8,
          "text-padding": 8,
        },
        paint: { "text-color": C.parkLabel, "text-halo-color": halo(C.park, "cc"), "text-halo-width": 1.2 },
      },
      {
        id: "neighborhood-label",
        type: "symbol",
        source: "basemap",
        "source-layer": "place",
        minzoom: 12,
        maxzoom: 16,
        filter: classIn(["neighbourhood", "suburb", "quarter"]),
        layout: {
          "text-field": ["get", "name"],
          "text-font": FONT.medium,
          "text-size": byZoom(12, 11, 15, 13.5),
          "text-letter-spacing": 0.02,
          "text-max-width": 7,
          "text-padding": 8,
        },
        paint: {
          "text-color": C.hood,
          "text-halo-color": halo(C.land),
          "text-halo-width": 1.4,
          "text-opacity": byZoom(15, 1, 16, 0),
        },
      },
      {
        id: "city-label",
        type: "symbol",
        source: "basemap",
        "source-layer": "place",
        maxzoom: 12,
        filter: classIn(["city", "town"]),
        layout: {
          "text-field": ["get", "name"],
          "text-font": FONT.semibold,
          "text-size": byZoom(6, 11, 11, 15),
          "text-max-width": 8,
        },
        paint: { "text-color": C.labelStrong, "text-halo-color": halo(C.land), "text-halo-width": 1.4 },
      },
      pinFootprintLayer(),
    ];
    return layers;
  },
};
